---
name: Deploy to AWS CloudFront
description:
inputs:
  bucket:
    description: S3 Bucket Name
    required: true
  cf_dist:
    description: CloudFront distribution
    required: true
  source_dir:
    description: Source directory
    required: false
    default: dist
runs:
  using: 'composite'
  steps:
    - run: aws s3 sync ${{ inputs.source_dir }} s3://${{ inputs.bucket }} --delete --no-progress --region eu-west-1
      shell: bash
    - run: aws cloudfront create-invalidation --distribution-id ${{ inputs.cf_dist }} --paths "/css" "/fonts" "/images" "/js" "/favicon.ico" "/index.html"
      shell: bash
